#!/usr/bin/env python
import os
import runpy

PKG = 'circus'

#try:
#    run_globals = runpy.run_module(PKG, run_name='__main__', alter_sys=True)
#except ImportError:  # For Python 2.6 compatibility
#    runpy.run_module('%s.__main__' % PKG, run_name='__main__', alter_sys=True)

runpy._run_module_as_main('%s.__main__' % PKG)
